### ISSUE TITLE
sei() and cli() not recognised when compiling for Due

### ISSUE THREAD

**Issue by GitLang** [MarkusLange/OneWireSlave#3]
Seems it is necessary to use interrupts() instead of sei() and noInterrupts() instead of cli() in OneWireSlave.cpp. Then it will compile fine in ARM mode for Due with Arduino 1.5.7, otherwise cli) and sei() are not recognised.

Git

**Comment by MarkusLange** [comment]
Yes you are right I will change that

**Comment by MarkusLange** [comment]
Done
